# Generated by Django 6.0.3 on 2026-03-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_category_description_category_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main Category', 'verbose_name_plural': '1. Main Categories'},
        ),
    ]
