# Generated by Django 6.0.3 on 2026-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_main',
            field=models.BooleanField(default=False, verbose_name='Image Main'),
        ),
    ]
