# Generated by Django 6.0.3 on 2026-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_category_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maincategory_images/'),
        ),
    ]
